import Image from "next/image";import Link from "next/link";
export const metadata={title:"Blog",description:"Relații, comunicare, familie, bani și gânduri personale — Cafea în Doi",alternates:{canonical:"/blog"}};
const logo="/images/ChatGPT Image 20 sept. 2026, 20_47_04.png";
const cats=[
["❤️","Relații și compatibilitate","Fidelitate, încredere, limite, valori și ce înseamnă pentru mine o relație serioasă."],
["💬","Comunicare și conflicte","Cum văd dialogul, neînțelegerile, compromisul, gelozia și relația la distanță."],
["👨‍👩‍👧","Familie și viitor","Copii, căsătorie, locuință, responsabilități și planurile unei vieți construite împreună."],
["💶","Bani în cuplu","Buget, economii, datorii, diferențe de venit, locuință și responsabilitate financiară."],
["☕","Viața mea și Cafea în Doi","Experiențele mele, munca, viața în străinătate, proiectele și felul în care văd viitorul."]
];
export default function Blog(){return <><header><div className="wrap"><nav><Link className="brand logo-link" href="/"><Image className="site-logo" src={logo} width={1536} height={512} alt="Cafea în Doi"/></Link><div className="links"><Link href="/">Acasă</Link><Link href="/povestea-mea">Povestea mea</Link><Link href="/intre-noi-doi">Între Noi Doi</Link><Link href="/contact">Contact</Link></div></nav></div></header><main className="story blog-page"><div className="eyebrow">Cafea în Doi · Blog</div><h1>Gânduri despre viață și relații</h1><p>Aici scriu despre lucrurile care contează pentru mine. Nu ca expert, ci din perspectiva mea — ca să poți afla mai multe despre omul din spatele Cafea în Doi.</p><div className="blog-categories">{cats.map(([icon,title,desc],i)=><section className="blog-category" key={title}><div className="blog-icon">{icon}</div><div><span className="eyebrow">Categoria {i+1}</span><h2>{title}</h2><p>{desc}</p><span className="article-count">10 articole planificate</span></div></section>)}</div><section className="blog-cta"><h2>☕ Înainte de prima cafea</h2><p>Dacă vrei să vezi cât de apropiate sunt răspunsurile noastre despre relație, familie, bani și viitor, încearcă „Între Noi Doi”.</p><Link className="btn" href="/intre-noi-doi">Descoperă Între Noi Doi</Link></section></main><footer><div className="wrap footer"><span>© 2026 Cafea în Doi</span><div className="links"><Link href="/termeni">Termeni</Link><Link href="/confidentialitate">Confidențialitate</Link><Link href="/cookies">Cookies</Link><Link href="/contact">Contact</Link><Link href="/admin/profil-compatibilitate">Privat</Link></div></div></footer></>}