import Image from "next/image";import Link from "next/link";
export const metadata={title:"Blog",description:"Relații, comunicare, familie, bani și gânduri personale — Cafea în Doi",alternates:{canonical:"/blog"}};
const logo="/images/ChatGPT Image 20 sept. 2026, 20_47_04.png";
const cats=[
{icon:"❤️",title:"Relații și compatibilitate",desc:"Fidelitate, încredere, limite, valori și ce înseamnă pentru mine o relație serioasă.",articles:["Ce înseamnă pentru mine o relație serioasă","De ce fidelitatea este esențială pentru mine","Ce caut la femeia cu care mi-aș construi viața","Atracția este suficientă pentru o relație?","Ce înseamnă pentru mine încrederea într-un cuplu","Câtă libertate ar trebui să avem într-o relație","Ce lucruri nu aș putea accepta într-o relație","De ce prefer o singură persoană potrivită în locul sutelor de match-uri","Compatibilitate sau compromis: unde este limita?","De ce am creat „Între Noi Doi” și cele 100 de întrebări"]},
{icon:"💬",title:"Comunicare și conflicte",desc:"Cum văd dialogul, neînțelegerile, compromisul, gelozia și relația la distanță.",articles:["Cum cred că trebuie rezolvată o ceartă în cuplu","De ce prefer să spun direct când ceva mă deranjează","Este normal să avem opinii diferite într-o relație","Ce înseamnă pentru mine un compromis sănătos","Gelozie sau grijă: unde văd eu diferența","De ce telefonul partenerului nu trebuie să devină instrument de control","Când unul are nevoie de spațiu după o ceartă","Cum văd eu o relație la distanță","De ce este important să putem spune „am greșit”","Lucrurile pe care nu ar trebui să ni le spunem nici măcar când suntem nervoși"]},
{icon:"👨‍👩‍👧",title:"Familie și viitor",desc:"Copii, căsătorie, locuință, responsabilități și planurile unei vieți construite împreună.",articles:["Ce înseamnă familia pentru mine","Cum m-a schimbat faptul că am devenit tată","Mi-aș dori să mai am copii?","Cum văd eu rolurile într-o familie modernă","Căsătoria: importantă sau doar o formalitate?","Cum cred că trebuie împărțită creșterea copiilor","Cât de mult ar trebui să se implice părinții noștri în relație","Cum îmi imaginez casa și familia mea peste zece ani","De ce stabilitatea contează înainte de a construi o familie","Ce aș vrea să le ofer copiilor mei în viitor"]},
{icon:"💶",title:"Bani în cuplu",desc:"Buget, economii, datorii, diferențe de venit, locuință și responsabilitate financiară.",articles:["Cum văd eu banii într-o relație serioasă","Cont comun sau conturi separate?","Cum împărțim cheltuielile dacă unul câștigă mai mult","De ce partenerii trebuie să vorbească deschis despre datorii","Cât ar trebui să economisească o familie în fiecare lună","Fondul de urgență: de ce îl consider important","Chirie sau locuință proprie: cum gândesc eu","Când merită să faci un credit și când nu","Afacerea unuia dintre parteneri: risc personal sau proiect de familie?","Ce înseamnă pentru mine independența financiară într-un cuplu"]},
{icon:"☕",title:"Viața mea și Cafea în Doi",desc:"Experiențele mele, munca, viața în străinătate, proiectele și felul în care văd viitorul.",articles:["De ce am creat Cafea în Doi","Cine sunt eu dincolo de fotografia de pe prima pagină","De la Brăila la Cehia și Germania: drumul meu până aici","Ce m-a învățat meseria de sudor despre viață","De ce nu fumez și nu consum alcool","Ce rol au fitnessul și sănătatea în viața mea","De ce sunt atât de interesat de tehnologie","Ce construiesc pentru viitor și de ce muncesc atât de mult","Ce am învățat din relațiile și experiențele mele de până acum","Cum îmi imaginez prima noastră cafea"]}
];
export default function Blog(){return <><header><div className="wrap"><nav><Link className="brand logo-link" href="/"><Image className="site-logo" src={logo} width={1536} height={512} alt="Cafea în Doi"/></Link><div className="links"><Link href="/">Acasă</Link><Link href="/povestea-mea">Povestea mea</Link><Link href="/intre-noi-doi">Între Noi Doi</Link><Link href="/contact">Contact</Link></div></nav></div></header><main className="story blog-page"><div className="eyebrow">Cafea în Doi · Blog</div><h1>Gânduri despre viață și relații</h1><p>Aici scriu despre lucrurile care contează pentru mine. Nu ca expert, ci din perspectiva mea — ca să poți afla mai multe despre omul din spatele Cafea în Doi.</p><div className="blog-categories">{cats.map((cat,i)=><section className="blog-category blog-category-full" key={cat.title}><div className="blog-icon">{cat.icon}</div><div><span className="eyebrow">Categoria {i+1}</span><h2>{cat.title}</h2><p>{cat.desc}</p><ol className="article-list">{cat.articles.map((a,j)=>{const first=i===0&&j===0;return <li key={a}><span>{i*10+j+1}</span>{first?<Link href="/blog/ce-inseamna-pentru-mine-o-relatie-serioasa">{a}</Link>:a}<em className={first?"published":""}>{first?"Publicat":"În pregătire"}</em></li>})}</ol></div></section>)}</div><section className="blog-cta"><h2>☕ Înainte de prima cafea</h2><p>Dacă vrei să vezi cât de apropiate sunt răspunsurile noastre despre relație, familie, bani și viitor, încearcă „Între Noi Doi”.</p><Link className="btn" href="/intre-noi-doi">Descoperă Între Noi Doi</Link></section></main><footer><div className="wrap footer"><span>© 2026 Cafea în Doi</span><div className="links"><Link href="/termeni">Termeni</Link><Link href="/confidentialitate">Confidențialitate</Link><Link href="/cookies">Cookies</Link><Link href="/contact">Contact</Link><Link href="/admin/profil-compatibilitate">Privat</Link></div></div></footer></>}