import MobileNav from "../../components/MobileNav";
import Image from "next/image"; import Link from "next/link";
export const metadata={title:"Politica de confidențialitate",description:"Cum sunt colectate, folosite, protejate și șterse datele personale trimise prin Cafea în Doi.",alternates:{canonical:"/confidentialitate"}};
export default function Page(){return <><header><div className="wrap"><nav><Link className="brand logo-link" href="/" aria-label="Cafea în Doi — pagina principală"><Image className="site-logo" src="/images/ChatGPT Image 20 sept. 2026, 20_47_04.webp" width={1536} height={512} alt="Cafea în Doi — Mai mult decât o cafea"/></Link><div className="links"><Link href="/">Acasă</Link><Link href="/povestea-mea">Povestea mea</Link><Link href="/intre-noi-doi">Între Noi Doi</Link><Link href="/blog">Gândurile mele</Link><Link href="/#invitatie">Bem o cafea?</Link><Link href="/contact">Contact</Link></div><MobileNav/></nav></div></header><main className="story"><h1>Politica de confidențialitate</h1>
<p><strong>Ultima actualizare: 24 septembrie 2026</strong></p>
<h2>1. Cine administrează datele</h2>
<p>Cafea în Doi este o pagină personală administrată de Adrian. Pentru solicitări privind datele tale personale, folosește datele de contact publicate în pagina Contact.</p>
<h2>2. Ce date sunt colectate</h2>
<p>Prin formularul de invitație sunt colectate: prenumele, vârsta, localitatea, țara, adresa de email, selfie-ul sau videoul mut de verificare live, ziua și ora propuse pentru cafea (dacă programările sunt deschise), textul introdus în câmpul „Spune-mi puțin despre tine”, precum și confirmările privind vârsta minimă și citirea politicii de confidențialitate. Dacă invitația continuă, pot fi păstrate etapa relației, numărul conversațiilor online, provocările reciproce acceptate sau refuzate, detaliile unei întâlniri fizice confirmate și planificarea unei experiențe comune, precum tipul activității, destinația, perioada și bugetul convenit. Materialul de verificare live este obligatoriu pentru trimiterea invitației, nu este folosit pentru identificare biometrică și nu este publicat. Prin formularul „Ce părere ai?” de sub articole și declarații pot fi colectate prenumele, opinia scrisă și acordul pentru moderare și eventuală publicare. Pentru funcția de apreciere a declarațiilor, browserul păstrează local un identificator aleatoriu pentru a limita aprecierea repetată de pe același browser. Dacă administratorul activează notificările push în browser, site-ul stochează privat abonamentul browserului (adresa tehnică de livrare și cheile de criptare) și îl folosește doar pentru notificări despre invitații noi. Furnizorul de notificări al browserului livrează mesajul. Furnizorii tehnici pot prelucra și date tehnice, precum adresa IP, data și ora solicitării, informații despre browser și dispozitiv și jurnale necesare securității și funcționării serviciului.</p>
<h2>3. Scopul și temeiul prelucrării</h2>
<p>Datele introduse în formularul de invitație sunt folosite pentru primirea, evaluarea și, dacă există interes reciproc, continuarea invitației, organizarea conversațiilor online și a întâlnirilor fizice și trimiterea confirmării zilei, orei și locației pe email. Dacă Adrian acceptă invitația, persoana invitată poate primi acces la spațiul privat „Povestea noastră”. Contul nu poate fi creat liber. Parola este stocată numai într-o formă derivată criptografic, nu ca text, iar sesiunea de autentificare este păstrată într-un cookie securizat. Locația exactă a unei întâlniri fizice este transmisă și afișată numai după confirmarea întâlnirii. Opiniile trimise sub articole și declarații sunt folosite pentru moderare și, dacă sunt aprobate, pentru publicare alături de prenumele autorului. Identificatorul aleatoriu pentru aprecieri este folosit doar pentru funcționarea contorului de aprecieri și prevenirea abuzului. Pentru datele furnizate voluntar prin formulare, temeiul principal este consimțământul tău. Datele tehnice strict necesare pot fi prelucrate pentru funcționarea, securitatea și prevenirea abuzului, pe baza interesului legitim, în măsura permisă de lege.</p>
<h2>4. Cum circulă datele</h2>
<p>Formularele sunt găzduite prin infrastructura Vercel. Datele aplicației și materialul vizual de verificare sunt păstrate privat în Supabase și pot fi consultate numai din zona de administrare autentificată. Datele text ale invitației și opiniile trimise sub articole sau declarații sunt transmise și prin serviciul de email Resend către căsuța poștală a administratorului pentru gestionare și moderare; selfie-ul sau videoul nu este atașat emailului. Datele nu sunt vândute și nu sunt folosite de Cafea în Doi pentru publicitate comportamentală.</p>
<h2>5. Transferuri internaționale</h2>
<p>Unii furnizori tehnici operează și în afara Spațiului Economic European. Resend declară că stochează datele clienților în Statele Unite și utilizează mecanisme precum Clauzele Contractuale Standard și EU-U.S. Data Privacy Framework pentru transferurile relevante. Alegerea regiunii europene de trimitere a emailului nu înseamnă că toate datele sunt stocate în UE.</p>
<h2>6. Cât timp sunt păstrate datele</h2>
<p>Invitațiile care nu intră în conversație și nu au un cont privat activ sunt eliminate automat din dashboard, împreună cu selfie-ul sau videoul, după 90 de zile. Opiniile trimise pentru moderare sunt păstrate cât este necesar pentru verificare; dacă o opinie este publicată, prenumele și textul opiniei pot rămâne publice până la retragerea acordului sau până când nu mai sunt necesare. Dacă conversația continuă, datele relevante pot fi păstrate atât timp cât este necesar relației și apoi șterse când nu mai sunt necesare. Resend declară o perioadă standard de păstrare de 30 de zile pentru conținutul emailurilor și loguri pe planurile Free, Pro și Scale. Furnizorii tehnici pot păstra anumite loguri și metadate potrivit propriilor obligații și politici.</p>
<h2>7. Drepturile tale</h2>
<p>În condițiile GDPR, poți solicita accesul la date, rectificarea, ștergerea, restricționarea prelucrării, portabilitatea datelor și poți formula o opoziție atunci când prelucrarea se bazează pe interes legitim. Când prelucrarea se bazează pe consimțământ, îl poți retrage pentru viitor. De asemenea, ai dreptul să depui o plângere la autoritatea de supraveghere competentă.</p>
<h2>8. Caracterul voluntar al datelor</h2>
<p>Trimiterea unei invitații este voluntară. Câmpurile marcate ca obligatorii sunt necesare pentru ca invitația să poată fi primită și evaluată; dacă nu dorești să le furnizezi, nu trimite formularul.</p>
<h2>9. Decizii automate</h2>
<p>Cafea în Doi nu folosește datele din formular pentru luarea de decizii exclusiv automatizate și nu realizează profilare în scop publicitar.</p>
<h2>10. Securitate</h2>
<p>Sunt utilizate conexiuni HTTPS/TLS și servicii tehnice care oferă măsuri de securitate pentru transmiterea datelor. Niciun sistem online nu poate garanta însă securitate absolută.</p>
<h2>11. Actualizări</h2>
<p>Politica poate fi actualizată dacă se modifică formularul, furnizorii sau modul de prelucrare. Data ultimei actualizări este afișată la începutul paginii.</p>
</main><footer><div className="wrap footer"><span>© 2026 Cafea în Doi</span><div className="links"><Link href="/termeni">Termeni</Link><Link href="/confidentialitate">Confidențialitate</Link><Link href="/cookies">Cookies</Link><Link href="/contact">Contact</Link></div></div></footer></>}
