import {cookies,headers} from "next/headers";
import {NextRequest,NextResponse} from "next/server";
import {readInvitation} from "../../../../lib/invitations";
import {PORTAL_COOKIE,verifyPortalSession} from "../../../../lib/portal-auth";
import {deleteSubscription,getPushKeys,saveSubscription,sendPush,validateSubscription} from "../../../../lib/push";
export const runtime="nodejs";
const allowedOrigin=(origin:string|null)=>!origin||origin==="https://www.cafeaindoi.eu"||origin==="https://cafeaindoi.eu";
async function identity(){const id=verifyPortalSession((await cookies()).get(PORTAL_COOKIE)?.value);if(!id)return null;const invitation=await readInvitation(id);return invitation?.portalAccessStatus==="active"?{id,invitation}:null}
export async function GET(){const user=await identity();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});try{const keys=await getPushKeys();return NextResponse.json({configured:true,publicKey:keys.publicKey},{headers:{"Cache-Control":"private, no-store"}})}catch{return NextResponse.json({error:"Notificările nu sunt disponibile momentan."},{status:503})}}
export async function POST(req:NextRequest){const user=await identity();if(!user||!allowedOrigin((await headers()).get("origin")))return NextResponse.json({error:"Unauthorized"},{status:401});try{const input=await req.json();if(input?.test===true)return NextResponse.json(await sendPush("Cafea în Doi","Notificările pentru Povestea noastră sunt active.",{url:"/povestea-noastra",tag:`test-partenera-${user.id}`,recipient:"partner",invitationId:user.id}));if(!validateSubscription(input))return NextResponse.json({error:"Abonament invalid."},{status:400});await saveSubscription({...input,createdAt:new Date().toISOString(),recipient:"partner",invitationId:user.id});return NextResponse.json({ok:true})}catch(error){console.error("[portal/push] SAVE_ERROR",error);return NextResponse.json({error:"Notificările nu au putut fi activate."},{status:503})}}
export async function DELETE(req:NextRequest){const user=await identity();if(!user||!allowedOrigin((await headers()).get("origin")))return NextResponse.json({error:"Unauthorized"},{status:401});try{const {endpoint}=await req.json();if(typeof endpoint!=="string")return NextResponse.json({error:"Date invalide."},{status:400});await deleteSubscription(endpoint,{recipient:"partner",invitationId:user.id});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"Dezactivarea a eșuat."},{status:503})}}
