import MobileNav from "../components/MobileNav";
import InvitationForm from "../components/InvitationForm";
import Image from "next/image";
import Link from "next/link";
import {listDeclarations} from "../lib/declarations";
export const metadata={alternates:{canonical:"/"}};
const logo="/images/ChatGPT Image 20 sept. 2026, 20_47_04.png";
export default async function Home(){let declarations:any[]=[];try{declarations=(await listDeclarations("published")).slice(0,3)}catch{}return <><header><div className="wrap"><nav><Link href="/" className="brand logo-link" aria-label="Cafea în Doi — pagina principală"><Image className="site-logo" src={logo} width={1536} height={512} priority alt="Cafea în Doi — Mai mult decât o cafea"/></Link><div className="links"><Link href="/povestea-mea">Povestea mea</Link><Link href="/intre-noi-doi">Între Noi Doi</Link><Link href="/blog">Gândurile mele</Link><Link href="/declaratii">Declarații</Link><Link href="/contact">Contact</Link></div><MobileNav/></nav></div></header><main className="wrap hero"><section className="profile"><Image className="portrait" src="/images/01_cafea_in_doi.png" width={800} height={1200} priority alt="Adrian — Cafea în Doi"/><div><div className="eyebrow">cafeaindoi.eu</div><h1>Cafea în Doi</h1><div className="tag">Prima cafea o bem online.</div><div className="home-purpose"><h2>Cunoaște-mă înainte să bem cafeaua</h2><p>Am creat acest loc pentru ca tu să afli cine sunt, cum gândesc și ce îmi doresc de la o relație. Citește în ritmul tău. Dacă simți că avem lucruri importante în comun, putem continua conversația la o cafea.</p></div><p><b>Salut, sunt Adrian.</b> Am 39 de ani, sunt român și locuiesc în Germania. Sunt tată, lucrez ca sudor, sunt pasionat de IT și îmi construiesc propriile planuri pentru viitor.</p><p><span className="pill">🇷🇴 Român</span><span className="pill">🇩🇪 Germania</span><span className="pill">🚭 Nu fumez</span><span className="pill">🥂 Fără alcool</span></p><div className="quote">Nu caut sute de match-uri. Caut o singură persoană potrivită.</div><Link className="btn alt" href="/povestea-mea">❤️ Citește povestea mea</Link></div></section><section className="card" id="invitatie"><div className="eyebrow">invitație personală</div><h2>☕ Bem o cafea?</h2><p>Dacă și tu cauți o relație serioasă, spune-mi câteva lucruri despre tine. Dacă există interes reciproc, continuăm pe WhatsApp.</p><InvitationForm/></section></main>{declarations.length>0&&<section className="wrap declaration-home"><div className="declaration-home-head"><div><div className="eyebrow">Cuvinte scrise de mine</div><h2>Ultimele declarații</h2></div><Link href="/declaratii">Vezi toate →</Link></div><div className="declaration-home-grid">{declarations.map((d:any)=><Link key={d.id} className="declaration-home-card" href={"/declaratii/"+d.slug}><span>{d.category}</span><h3>{d.title}</h3><p>{d.text.length>150?d.text.slice(0,150)+"…":d.text}</p></Link>)}</div></section>}<Footer/></>}
function Footer(){return <footer><div className="wrap footer"><span>© 2026 Cafea în Doi</span><div className="links"><Link href="/termeni">Termeni</Link><Link href="/confidentialitate">Confidențialitate</Link><Link href="/cookies">Cookies</Link><Link href="/contact">Contact</Link><Link href="/admin">Privat</Link></div></div></footer>}
