"use client";
import {useEffect,useMemo,useState} from "react";
import type {ContactMessage,ContactSettings,ContactStatus} from "../lib/contact";
type Data={messages:ContactMessage[];settings:ContactSettings};type Tab=ContactStatus|"all"|"settings";
const labels:Record<ContactStatus,string>={new:"Nou",in_progress:"În lucru",resolved:"Rezolvat",archived:"Arhivat"};
export default function AdminContact(){const [data,setData]=useState<Data|null>(null),[tab,setTab]=useState<Tab>("new"),[query,setQuery]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function load(){setError("");try{const response=await fetch("/api/admin/contact",{cache:"no-store"}),value=await response.json();if(!response.ok)throw Error(value.error);setData(value)}catch(reason){setError(reason instanceof Error?reason.message:"Mesajele nu pot fi încărcate.")}}
 useEffect(()=>{load()},[]);
 async function saveMessage(item:ContactMessage,status=item.status){setBusy(item.id);setError("");setNotice("");try{const response=await fetch("/api/admin/contact",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,status,internalNote:item.internalNote})}),value=await response.json();if(!response.ok)throw Error(value.error);setData(current=>current?{...current,messages:current.messages.map(message=>message.id===item.id?value.message:message)}:current);setNotice("Mesajul a fost actualizat.")}catch(reason){setError(reason instanceof Error?reason.message:"Salvarea nu a reușit.")}finally{setBusy("")}}
 async function saveSettings(){if(!data)return;setBusy("settings");setError("");setNotice("");try{const response=await fetch("/api/admin/contact",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"settings",settings:data.settings})}),value=await response.json();if(!response.ok)throw Error(value.error);setData({...data,settings:value.settings});setNotice("Setările de contact au fost salvate.")}catch(reason){setError(reason instanceof Error?reason.message:"Setările nu au fost salvate.")}finally{setBusy("")}}
 function patchMessage(id:string,internalNote:string){setData(current=>current?{...current,messages:current.messages.map(item=>item.id===id?{...item,internalNote}:item)}:current)}
 function patchSetting(key:keyof ContactSettings,value:string|boolean){setData(current=>current?{...current,settings:{...current.settings,[key]:value}}:current)}
 const counts=useMemo(()=>data?data.messages.reduce((result,item)=>({...result,[item.status]:result[item.status]+1}),{new:0,in_progress:0,resolved:0,archived:0}):{new:0,in_progress:0,resolved:0,archived:0},[data]);
 const filtered=useMemo(()=>{if(!data)return[];const q=query.trim().toLocaleLowerCase("ro");return data.messages.filter(item=>(tab==="all"||tab==="settings"||item.status===tab)&&(!q||[item.name,item.email,item.subject,item.message].join(" ").toLocaleLowerCase("ro").includes(q)))},[data,tab,query]);
 if(!data)return <div className="admin-empty">{error?<p className="formerror">{error}</p>:<><div className="admin-empty-icon">…</div><strong>Se încarcă mesajele</strong></>}</div>;
 return <div className="contact-admin">{notice?<p className="settings-success" role="status">✓ {notice}</p>:null}{error?<p className="formerror" role="alert">{error}</p>:null}<div className="contact-admin-kpis"><button onClick={()=>setTab("new")} className={tab==="new"?"active":""}><span>●</span><strong>{counts.new}</strong><small>Noi</small></button><button onClick={()=>setTab("in_progress")} className={tab==="in_progress"?"active":""}><span>◷</span><strong>{counts.in_progress}</strong><small>În lucru</small></button><button onClick={()=>setTab("resolved")} className={tab==="resolved"?"active":""}><span>✓</span><strong>{counts.resolved}</strong><small>Rezolvate</small></button><button onClick={()=>setTab("all")} className={tab==="all"?"active":""}><span>Σ</span><strong>{data.messages.length}</strong><small>Total</small></button></div>
  <div className="contact-admin-toolbar"><div><button className={tab!=="settings"?"active":""} onClick={()=>setTab("new")}>Mesaje</button><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>Setări publice</button></div>{tab!=="settings"?<><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Caută în mesaje…"/></label><a href="/api/admin/contact?format=csv">Export CSV ↓</a></>:null}</div>
  {tab==="settings"?<Settings settings={data.settings} patch={patchSetting} save={saveSettings} busy={busy==="settings"}/>:filtered.length?<div className="contact-message-list">{filtered.map(item=><article key={item.id} className="contact-message-card"><header><div className="admin-opinion-person"><span className="admin-avatar">{item.name.slice(0,1).toUpperCase()}</span><div><strong>{item.name}</strong><a href={`mailto:${item.email}`}>{item.email}</a><small>{new Date(item.createdAt).toLocaleString("ro-RO")}</small></div></div><select aria-label="Stare mesaj" value={item.status} onChange={event=>saveMessage(item,event.target.value as ContactStatus)}><option value="new">Nou</option><option value="in_progress">În lucru</option><option value="resolved">Rezolvat</option><option value="archived">Arhivat</option></select></header><h2>{item.subject}</h2><p>{item.message}</p><div className="contact-message-reply"><a className="btn" href={`mailto:${item.email}?subject=${encodeURIComponent(`Re: ${item.subject}`)}`}>Răspunde pe email</a></div><label>Notiță internă<textarea maxLength={3000} value={item.internalNote} onChange={event=>patchMessage(item.id,event.target.value)} placeholder="Adaugă context care rămâne doar în Admin…"/></label><button className="admin-action secondary" disabled={busy===item.id} onClick={()=>saveMessage(item)}>{busy===item.id?"Se salvează…":"Salvează notița"}</button></article>)}</div>:<div className="admin-empty"><div className="admin-empty-icon">✓</div><strong>Nu există mesaje aici</strong><p>{query?"Încearcă alt termen de căutare.":`Niciun mesaj cu starea „${tab==="all"?"toate":labels[tab as ContactStatus]}”.`}</p></div>}
 </div>}
function Settings({settings,patch,save,busy}:{settings:ContactSettings;patch:(key:keyof ContactSettings,value:string|boolean)=>void;save:()=>void;busy:boolean}){return <section className="settings-card contact-settings"><header><h2>Pagina publică de contact</h2><p>Controlează formularul, datele afișate și mesajele văzute de vizitatori.</p></header><label className="settings-toggle"><span><strong>Formular activ</strong><small>Permite vizitatorilor să trimită mesaje noi.</small></span><input type="checkbox" checked={settings.enabled} onChange={event=>patch("enabled",event.target.checked)}/><i aria-hidden="true"/></label><div className="settings-form-grid"><label className="wide">Text introductiv<textarea maxLength={500} value={settings.intro} onChange={event=>patch("intro",event.target.value)}/></label><label className="wide">Mesaj după trimitere<textarea maxLength={300} value={settings.successMessage} onChange={event=>patch("successMessage",event.target.value)}/></label><label>Email public<input type="email" value={settings.email} onChange={event=>patch("email",event.target.value)}/></label><label>Telefon<input value={settings.phone} onChange={event=>patch("phone",event.target.value)}/></label><label>WhatsApp<input value={settings.whatsapp} onChange={event=>patch("whatsapp",event.target.value)}/></label><label>Program de răspuns<input maxLength={160} value={settings.responseHours} onChange={event=>patch("responseHours",event.target.value)}/></label><label>Facebook<input type="url" placeholder="https://…" value={settings.facebook} onChange={event=>patch("facebook",event.target.value)}/></label><label>Instagram<input type="url" placeholder="https://…" value={settings.instagram} onChange={event=>patch("instagram",event.target.value)}/></label><label>TikTok<input type="url" placeholder="https://…" value={settings.tiktok} onChange={event=>patch("tiktok",event.target.value)}/></label></div><div className="settings-save"><button type="button" disabled={busy} onClick={save}>{busy?"Se salvează…":"Salvează setările"}</button></div></section>}
