"use client";

import {useCallback,useEffect,useRef,useState} from "react";
import type {AudioCallSignal} from "../lib/audio-call";

const iceServers=[{urls:["stun:stun.l.google.com:19302","stun:stun1.l.google.com:19302"]}];
const waitForIce=(pc:RTCPeerConnection)=>pc.iceGatheringState==="complete"?Promise.resolve():new Promise<void>(resolve=>{const change=()=>{if(pc.iceGatheringState==="complete"){pc.removeEventListener("icegatheringstatechange",change);resolve()}};pc.addEventListener("icegatheringstatechange",change);window.setTimeout(()=>{pc.removeEventListener("icegatheringstatechange",change);resolve()},5000)});
type Props={endpoint:string;role:"adrian"|"ea";partnerName:string;startKey:number};

export default function AudioCall({endpoint,role,partnerName,startKey}:Props){
 const [signal,setSignal]=useState<AudioCallSignal|null>(null),[phase,setPhase]=useState<"idle"|"calling"|"incoming"|"connecting"|"connected">("idle"),[error,setError]=useState(""),[muted,setMuted]=useState(false),[cameraOff,setCameraOff]=useState(false),[seconds,setSeconds]=useState(0);
 const pcRef=useRef<RTCPeerConnection|null>(null),streamRef=useRef<MediaStream|null>(null),localVideoRef=useRef<HTMLVideoElement>(null),remoteVideoRef=useRef<HTMLVideoElement>(null),callIdRef=useRef(""),handledStartRef=useRef(0);
 const api=useCallback(async(body?:Record<string,unknown>)=>{const response=await fetch(endpoint,{method:body?"PATCH":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify({...body,conversationId:new URL(endpoint,location.origin).searchParams.get("id")}):undefined,cache:"no-store"}),data=await response.json();if(!response.ok)throw Error(data.error||"Apelul nu poate continua.");return data},[endpoint]);
 const cleanup=useCallback(()=>{pcRef.current?.close();pcRef.current=null;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(localVideoRef.current)localVideoRef.current.srcObject=null;if(remoteVideoRef.current)remoteVideoRef.current.srcObject=null;callIdRef.current="";setSignal(null);setPhase("idle");setSeconds(0);setMuted(false);setCameraOff(false)},[]);
 const prepare=useCallback(async()=>{if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection==="undefined")throw Error("Browserul nu permite apeluri video.");const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}}}),pc=new RTCPeerConnection({iceServers});stream.getTracks().forEach(track=>pc.addTrack(track,stream));if(localVideoRef.current)localVideoRef.current.srcObject=stream;pc.ontrack=event=>{if(remoteVideoRef.current){remoteVideoRef.current.srcObject=event.streams[0];void remoteVideoRef.current.play().catch(()=>{})}};pc.onconnectionstatechange=()=>{if(pc.connectionState==="connected")setPhase("connected");if(["failed","closed","disconnected"].includes(pc.connectionState))setError("Conexiunea video s-a întrerupt.")};streamRef.current=stream;pcRef.current=pc;return pc},[]);
 const start=useCallback(async()=>{if(phase!=="idle")return;setError("");setPhase("calling");try{const pc=await prepare(),offer=await pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await pc.setLocalDescription(offer);await waitForIce(pc);const data=await api({action:"audio_offer",offer:pc.localDescription});callIdRef.current=data.audioCall.id;setSignal(data.audioCall)}catch(reason){setError(reason instanceof Error?reason.message:"Camera sau microfonul nu au putut fi pornite.");cleanup()}},[api,cleanup,phase,prepare]);
 useEffect(()=>{if(startKey>handledStartRef.current){handledStartRef.current=startKey;void start()}},[startKey,start]);
 useEffect(()=>{if(localVideoRef.current&&streamRef.current)localVideoRef.current.srcObject=streamRef.current},[phase]);
 useEffect(()=>{let active=true;const poll=async()=>{try{const data=await api();if(!active)return;const next=data.audioCall as AudioCallSignal|null;if(!next)return;if(next.state==="ended"&&next.id===callIdRef.current){cleanup();return}if(next.state==="ringing"&&next.caller!==role&&phase==="idle"){callIdRef.current=next.id;setSignal(next);setPhase("incoming")}if(next.state==="connected"&&next.caller===role&&next.answer&&pcRef.current&&pcRef.current.remoteDescription===null){await pcRef.current.setRemoteDescription(next.answer);setSignal(next);setPhase("connecting")}}catch{} };void poll();const timer=window.setInterval(poll,1500);return()=>{active=false;window.clearInterval(timer)}},[api,cleanup,phase,role]);
 useEffect(()=>{if(phase!=="connected")return;const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer)},[phase]);
 useEffect(()=>()=>cleanup(),[cleanup]);
 async function accept(){if(!signal?.offer)return;setError("");setPhase("connecting");try{const pc=await prepare();await pc.setRemoteDescription(signal.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await waitForIce(pc);const data=await api({action:"audio_answer",callId:signal.id,answer:pc.localDescription});setSignal(data.audioCall)}catch(reason){setError(reason instanceof Error?reason.message:"Apelul nu a putut fi preluat.");await end()}}
 async function end(){const id=callIdRef.current;cleanup();if(id)try{await api({action:"audio_end",callId:id})}catch{}}
 function toggleMute(){const next=!muted;streamRef.current?.getAudioTracks().forEach(track=>{track.enabled=!next});setMuted(next)}
 function toggleCamera(){const next=!cameraOff;streamRef.current?.getVideoTracks().forEach(track=>{track.enabled=!next});setCameraOff(next)}
 const clock=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
 return <>{error&&phase==="idle"?<p className="formerror audio-call-error" role="alert">{error}</p>:null}{phase!=="idle"?<div className="audio-call-overlay" role="dialog" aria-modal="true" aria-label="Apel video"><div className="audio-call-dialog"><div className="video-call-stage"><video ref={remoteVideoRef} className="remote-video" autoPlay playsInline/><video ref={localVideoRef} className="local-video" autoPlay playsInline muted/>{phase!=="connected"?<div className="audio-call-avatar">{partnerName.slice(0,1).toUpperCase()}</div>:null}</div><span className="eyebrow">Cafea în Doi · apel video</span><h2>{partnerName}</h2><p>{phase==="incoming"?"Te sună…":phase==="calling"?"Se apelează…":phase==="connected"?clock:"Se conectează…"}</p>{error?<p className="formerror" role="alert">{error}</p>:null}<div className="audio-call-actions">{phase==="incoming"?<><button className="answer" onClick={()=>void accept()}>📹 Răspunde</button><button className="hangup" onClick={()=>void end()}>✕ Respinge</button></>:<><button className="mute" onClick={toggleMute}>{muted?"🔇 Pornește sunetul":"🎙 Oprește sunetul"}</button><button className="mute" onClick={toggleCamera}>{cameraOff?"📷 Pornește camera":"📷 Oprește camera"}</button><button className="hangup" onClick={()=>void end()}>☎ Închide</button></>}</div><small>Conexiune directă între cele două telefoane · fără înregistrare</small></div></div>:null}</>;
}
