"use client";
import {useMemo,useState} from "react";
type Q={t:string,c:number,target:number};
const cats=["❤️ Relație","💬 Comunicare","⚖️ Conflicte","💕 Afecțiune","👨‍👩‍👧 Familie","🌿 Stil de viață","🏠 Viața împreună","💶 Bani și muncă","🌍 Viitor","🧭 Încredere"];
const groups=[
["Îmi doresc o relație serioasă și stabilă.","Fidelitatea este esențială pentru mine.","Sinceritatea contează chiar când adevărul este incomod.","Încrederea trebuie construită reciproc.","Îmi doresc o relație exclusivă.","Respectul trebuie păstrat și în dezacord.","Îmi doresc ca partenerul să fie și un prieten apropiat.","Este sănătos ca fiecare să păstreze o anumită independență.","Valorile comune sunt importante într-o relație.","Îmi doresc să construiesc o viață în doi pe termen lung."],
["Îmi place să vorbesc deschis despre ceea ce simt.","Pot spune direct când ceva mă deranjează.","Îmi doresc ca partenerul să vorbească despre emoțiile lui.","Este important să ne ascultăm fără să ne întrerupem.","Pot vorbi despre vulnerabilitățile mele.","Prefer să clarificăm neînțelegerile prin dialog.","Când povestesc o problemă, apreciez și empatia, nu doar soluțiile.","Îmi place să păstrăm legătura regulat când suntem la distanță.","Pot discuta subiecte dificile fără să evit conversația.","Vreau să putem vorbi fără teamă de judecată."],
["Prefer să rezolvăm conflictele fără jigniri.","Este important să ne cerem scuze când greșim.","Ridicarea tonului ar trebui evitată.","Sunt dispusă să fac compromisuri rezonabile.","Pot accepta că nu vom avea mereu aceeași opinie.","Nu cred că greșelile vechi trebuie folosite în certuri noi.","Pot oferi spațiu partenerului când are nevoie să se calmeze.","Încerc să înțeleg și perspectiva celuilalt.","Nu folosesc amenințarea cu despărțirea pentru a câștiga o ceartă.","După un conflict, este important să reparăm apropierea dintre noi."],
["Afecțiunea fizică zilnică este importantă pentru mine.","Îmi place să îi spun partenerului că îl apreciez.","Îmi place romantismul și după ce relația devine stabilă.","Îmi place să marcăm momentele importante pentru noi.","Vreau să avem întâlniri doar noi doi și după ani de relație.","Compatibilitatea intimă este importantă.","Pot vorbi deschis despre nevoile intime într-o relație.","Îmi place spontaneitatea în cuplu.","Îmi place să ofer și să primesc gesturi de afecțiune.","În perioade dificile vreau să păstrăm apropierea emoțională."],
["Îmi doresc copii în viitor.","Pot accepta că partenerul are deja un copil.","Aș vrea să am o relație bună cu copilul partenerului.","Îmi doresc să construiesc o familie.","Sunt deschisă ideii de căsătorie.","Este important să avem principii apropiate despre educația copiilor.","Responsabilitățile privind copiii trebuie împărțite echitabil.","Familiile extinse trebuie respectate fără să conducă relația noastră.","Aș susține relația dacă familia mea ar avea rezerve nejustificate.","Mi-ar plăcea să construim propriile tradiții de familie."],
["Prefer să nu fumez.","Prefer un consum de alcool foarte redus sau deloc.","Un stil de viață sănătos este important pentru mine.","Îmi place să includ mișcarea în viața mea.","Îmi place să petrec uneori weekendurile liniștit acasă.","Îmi plac și ieșirile sau activitățile în afara casei.","Îmi place să călătoresc din când în când.","Nu am nevoie de petreceri frecvente pentru a mă simți bine.","Pot respecta rutina și obiceiurile sănătoase ale partenerului.","Îmi place un echilibru între liniște și experiențe noi."],
["Curățenia în casă este importantă pentru mine.","Îmi place să existe un nivel rezonabil de ordine.","Treburile casei trebuie împărțite echitabil.","Pot contribui la gătit și activitățile gospodărești.","Am nevoie și de puțin timp personal când locuiesc cu cineva.","Îmi place să avem regulat momente sau mese împreună.","Deciziile importante ale casei trebuie luate împreună.","Pot negocia diferențele privind ordinea și rutina.","Îmi doresc activități comune în timpul liber.","Cred că fiecare trebuie să își păstreze și hobby-urile proprii."],
["Stabilitatea financiară este importantă pentru mine.","Banii trebuie discutați deschis într-o relație serioasă.","Este sănătos ca fiecare să păstreze și o anumită autonomie financiară.","Cheltuielile comune pot fi împărțite echitabil în funcție de situație.","Economisirea pentru viitor este importantă.","Datoriile importante trebuie discutate sincer.","Achizițiile mari trebuie discutate înainte.","Pot accepta perioade în care partenerul muncește mai mult pentru un obiectiv important.","Pot susține un proiect sau o afacere proprie a partenerului dacă există responsabilitate.","Dacă unul rămâne temporar fără venit, cuplul trebuie să se sprijine reciproc."],
["Aș lua în calcul să locuiesc într-o altă țară pentru o relație serioasă.","Locul în care vom trăi pe termen lung trebuie decis împreună.","Aș putea începe o viață nouă într-un alt oraș dacă avem un plan bun.","Îmi doresc un plan comun pentru următorii cinci ani.","Sunt deschisă ideii de a cumpăra cândva o locuință împreună.","Îmi doresc stabilitate înaintea deciziilor familiale majore.","Este important ca fiecare să își poată continua dezvoltarea profesională.","Pot negocia perioade în care cariera unuia necesită mai multă atenție.","Îmi doresc obiective financiare comune pe termen lung.","Îmi imaginez o viață stabilă în doi peste zece ani."],
["Respect intimitatea telefonului și mesajelor partenerului.","Pot avea încredere fără să verific permanent partenerul.","Gelozia nu trebuie să devină control.","Putem spune unde mergem din respect, nu din obligație.","Nu am nevoie să expun toată relația pe social media.","Îmi susțin partenerul când trece printr-o perioadă dificilă.","Accept că oamenii se schimbă și relația trebuie să evolueze.","Pot accepta diferențe care nu afectează valorile fundamentale.","Respect limitele personale ale partenerului.","Încrederea se construiește prin consecvență și respect reciproc."]
];
const adrianProfile=[5,5,5,5,5,5,5,4,5,5,5,5,4,5,4,5,4,4,5,5,5,5,5,5,4,4,5,5,5,5,4,4,4,3,4,4,4,3,4,5,5,5,5,5,4,5,5,4,4,5,5,5,5,4,5,4,4,5,5,4,5,4,5,4,4,5,5,4,4,4,5,5,4,4,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,4,4,5,4,4,5,5];
const qs:Q[]=groups.flatMap((g,c)=>g.map((t,i)=>({t,c,target:adrianProfile[c*10+i]})));
const pts=[0,2,5,8,10];
export default function CompatibilityTest(){const [a,setA]=useState<number[]>(Array(100).fill(0));const [step,setStep]=useState(0);const done=a.filter(Boolean).length;const result=useMemo(()=>{const by=Array(10).fill(0);a.forEach((v,i)=>{if(v)by[qs[i].c]+=pts[4-Math.abs(v-qs[i].target)]});return{by,total:by.reduce((x,y)=>x+y,0)}},[a]);const start=step*10;return <div className="compat"><div className="compat-progress"><span>{done}/100 răspunsuri</span><div><i style={{width:done+"%"}}/></div></div>{step<10?<><div className="eyebrow">{step+1}/10 · {cats[step]}</div><h2>{cats[step]}</h2><p>Alege cât de mult te reprezintă fiecare afirmație.</p>{qs.slice(start,start+10).map((q,j)=><fieldset className="compat-q" key={start+j}><legend>{start+j+1}. {q.t}</legend><div className="scale">{["Deloc","Puțin","Parțial","Mult","Complet"].map((x,k)=><label key={x} className={a[start+j]===k+1?"selected":""}><input type="radio" name={"q"+(start+j)} checked={a[start+j]===k+1} onChange={()=>{const n=[...a];n[start+j]=k+1;setA(n)}}/><span>{k+1}</span><small>{x}</small></label>)}</div></fieldset>)}<div className="compat-actions">{step>0&&<button className="btn alt" onClick={()=>setStep(step-1)}>← Înapoi</button>}<button className="btn" disabled={a.slice(start,start+10).some(v=>!v)} onClick={()=>setStep(step+1)}>{step===9?"Vezi rezultatul":"Continuă →"}</button></div></>:<><div className="eyebrow">Rezultatul tău</div><h2>{result.total} / 1.000 puncte</h2><p>Scorul arată apropierea răspunsurilor față de profilul de referință Cafea în Doi; nu prezice succesul unei relații.</p><div className="score-grid">{cats.map((c,i)=><div key={c}><strong>{c}</strong><span>{result.by[i]}/100</span></div>)}</div><div className="compat-actions"><button className="btn alt" onClick={()=>setStep(0)}>Revizuiește răspunsurile</button><a className="btn" href="/#invitatie">☕ Trimite invitația</a></div></>}</div>}