"use client";
import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import type {Conversation} from "../lib/conversation";
declare global{interface Window{MeteredFrame?:new()=>{init:(options:Record<string,unknown>,element:HTMLElement)=>Promise<void>|void;leaveMeeting?:()=>void}}}
type Props={role:"adrian"|"ea";invitationId?:string;partnerName:string};type Call={roomURL:string;accessToken:string};
export default function ConversationPanel({role,invitationId,partnerName}:Props){
 const endpoint=role==="adrian"?`/api/admin/conversatie?id=${encodeURIComponent(invitationId||"")}`:"/api/povestea-noastra/conversatie";
 const [conversation,setConversation]=useState<Conversation|null>(null),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[call,setCall]=useState<Call|null>(null);
 const expiry=useMemo(()=>conversation?.expiresAt?new Date(conversation.expiresAt).toLocaleString("ro-RO",{dateStyle:"short",timeStyle:"short"}):null,[conversation?.expiresAt]);
 async function load(){const r=await fetch(endpoint,{cache:"no-store"});if(r.ok)setConversation((await r.json()).conversation)}
 useEffect(()=>{load();const timer=window.setInterval(load,5000);return()=>window.clearInterval(timer)},[endpoint]);
 async function request(method:"POST"|"PATCH",body:Record<string,unknown>){setBusy(true);setError("");const r=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();setBusy(false);if(!r.ok){setError(data.error||"Acțiunea nu a reușit.");return null}if(data.conversation)setConversation(data.conversation);return data}
 async function send(e:FormEvent){e.preventDefault();if(!text.trim())return;const sent=await request("POST",{text});if(sent)setText("")}
 async function propose(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await request("PATCH",{action:"propose",startsAt:fd.get("startsAt"),plannedMinutes:Number(fd.get("plannedMinutes"))})}
 async function join(){const data=await request("PATCH",{action:"join"});if(data?.call)setCall(data.call)}const meeting=conversation?.meeting;
 return <section className="conversation-card"><header className="conversation-head"><div><span className="eyebrow">Doar voi doi</span><h2>Conversația noastră</h2></div><span className="conversation-private">🔒 Privat</span></header><p className="conversation-retention">Mesajele se șterg automat la 24 de ore după ultimul mesaj.{expiry&&<> Sesiunea curentă expiră la <strong>{expiry}</strong>.</>}</p>{error&&<p className="formerror" role="alert">{error}</p>}<div className="conversation-messages" aria-live="polite">{!conversation?.messages.length?<p className="conversation-empty">Începeți firesc — poate chiar cu invitația la o cafea.</p>:conversation.messages.map(message=><article className={message.sender===role?"mine":"theirs"} key={message.id}><strong>{message.sender===role?"Tu":partnerName}</strong><p>{message.text}</p><time>{new Date(message.createdAt).toLocaleTimeString("ro-RO",{hour:"2-digit",minute:"2-digit"})}</time></article>)}</div><form className="conversation-compose" onSubmit={send}><label className="sr-only" htmlFor={`message-${role}`}>Mesaj</label><textarea id={`message-${role}`} value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder={`Scrie-i ${partnerName==="Adrian"?"lui Adrian":partnerName+"…"}`} required/><button disabled={busy||!text.trim()}>Trimite</button></form><div className="coffee-call"><div className="coffee-call-title"><div><span>☕</span><div><b>O Cafea în Doi</b><small>Apel video privat, fără înregistrare</small></div></div>{meeting&&<em>{meeting.status}</em>}</div>{meeting?<div className="coffee-proposal"><p><strong>{new Date(meeting.startsAt).toLocaleString("ro-RO",{dateStyle:"full",timeStyle:"short"})}</strong><br/>Durată orientativă: {meeting.plannedMinutes} minute</p>{meeting.status==="propusa"&&meeting.proposer!==role&&<div><button onClick={()=>request("PATCH",{action:"respond",status:"acceptata"})} disabled={busy}>Accept</button><button className="ghost" onClick={()=>request("PATCH",{action:"respond",status:"refuzata"})} disabled={busy}>Refuz</button></div>}{meeting.status==="propusa"&&meeting.proposer===role&&<small>Așteptăm răspunsul.</small>}{meeting.status==="acceptata"&&<button className="coffee-start" onClick={join} disabled={busy}>Începe o Cafea în Doi</button>}<small>Durata este orientativă. Apelul nu se închide automat.</small></div>:<form className="coffee-propose" onSubmit={propose}><label>Data și ora<input name="startsAt" type="datetime-local" required/></label><label>Durată orientativă<select name="plannedMinutes" defaultValue="30"><option value="15">15 minute</option><option value="30">30 minute</option><option value="60">60 minute</option><option value="90">90 minute</option></select></label><button disabled={busy}>Propune o Cafea în Doi</button><small>Apelul poate continua oricât doriți; durata aleasă este doar orientativă.</small></form>}</div>{call&&<VideoCall call={call} close={()=>setCall(null)}/>}</section>
}
function VideoCall({call,close}:{call:Call;close:()=>void}){const host=useRef<HTMLDivElement>(null);useEffect(()=>{let frame:{init:(o:Record<string,unknown>,e:HTMLElement)=>Promise<void>|void;leaveMeeting?:()=>void}|undefined,cancelled=false;async function start(){if(!window.MeteredFrame)await new Promise<void>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[data-metered="true"]');if(existing){if(window.MeteredFrame)resolve();else existing.addEventListener("load",()=>resolve(),{once:true});return}const script=document.createElement("script");script.src="https://cdn.metered.ca/sdk/frame/1.4.3/sdk-frame.min.js";script.dataset.metered="true";script.onload=()=>resolve();script.onerror=()=>reject(new Error("SDK video indisponibil"));document.head.appendChild(script)});if(cancelled||!host.current||!window.MeteredFrame)return;frame=new window.MeteredFrame();await frame.init({roomURL:call.roomURL,accessToken:call.accessToken,width:"100%",height:"100%",autoJoin:true,joinVideoOn:false,joinAudioOn:false,showInviteBox:false,disableChat:true,disableScreenSharing:true},host.current)}start();return()=>{cancelled=true;frame?.leaveMeeting?.()}},[call]);return <div className="video-overlay" role="dialog" aria-modal="true" aria-label="Cafea în Doi"><div className="video-dialog"><header><div><b>☕ Cafea în Doi</b><small>Apelul nu se închide automat</small></div><button onClick={close} aria-label="Închide apelul">×</button></header><div ref={host} className="video-host"/></div></div>}
