"use client";
import Image from "next/image";
import {FormEvent,useEffect,useRef,useState} from "react";
import type {Conversation} from "../lib/conversation";

declare global{interface Window{MeteredFrame?:new()=>{init:(options:Record<string,unknown>,element:HTMLElement)=>Promise<void>|void;leaveMeeting?:()=>void}}}
type Props={role:"adrian"|"ea";invitationId?:string;partnerName:string};
type Call={roomURL:string;accessToken:string};

export default function ConversationPanel({role,invitationId,partnerName}:Props){
 const endpoint=role==="adrian"?`/api/admin/conversatie?id=${encodeURIComponent(invitationId||"")}`:"/api/povestea-noastra/conversatie";
 const [conversation,setConversation]=useState<Conversation|null>(null),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[call,setCall]=useState<Call|null>(null),[editMeeting,setEditMeeting]=useState(false),[now,setNow]=useState(Date.now());
 async function load(){const r=await fetch(endpoint,{cache:"no-store"});if(r.ok)setConversation((await r.json()).conversation)}
 useEffect(()=>{load();const poll=window.setInterval(load,5000),clock=window.setInterval(()=>setNow(Date.now()),60000);return()=>{window.clearInterval(poll);window.clearInterval(clock)}},[endpoint]);
 async function request(method:"POST"|"PATCH",body:Record<string,unknown>){setBusy(true);setError("");const r=await fetch(endpoint,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await r.json();setBusy(false);if(!r.ok){setError(data.error||"Acțiunea nu a reușit.");return null}if(data.conversation)setConversation(data.conversation);return data}
 async function send(e:FormEvent){e.preventDefault();if(!text.trim())return;const sent=await request("POST",{text});if(sent)setText("")}
 async function propose(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),data=await request("PATCH",{action:"propose",startsAt:fd.get("startsAt"),plannedMinutes:Number(fd.get("plannedMinutes"))});if(data)setEditMeeting(false)}
 async function join(){const data=await request("PATCH",{action:"join"});if(data?.call)setCall(data.call)}
 const meeting=conversation?.meeting,remaining=conversation?.expiresAt?Math.max(0,Date.parse(conversation.expiresAt)-now):0,hours=Math.floor(remaining/3600000),minutes=Math.floor(remaining%3600000/60000);
 const adrianPhoto="/images/ChatGPT Image 20 sept. 2026, 20_47_04.webp",guestPhoto=role==="adrian"&&invitationId?`/api/admin/invitatii/${invitationId}/photo`:"/images/cafeaindoi-icon.webp";
 function avatar(sender:"adrian"|"ea"){return sender==="adrian"?adrianPhoto:guestPhoto}
 return <section className="conversation-card conversation-preview">
  <header className="conversation-head"><span className="conversation-back">‹</span><div className="conversation-person"><Image src={avatar(role==="adrian"?"ea":"adrian")} alt="" width={58} height={58} unoptimized/><i/><div><h2>Conversația noastră</h2><span>🔒 Doar voi doi</span></div></div><button className="conversation-video-icon" onClick={meeting?.status==="acceptata"?join:()=>setEditMeeting(true)} aria-label="Apel video"><VideoGlyph/></button></header>
  <p className="conversation-retention">◷ <strong>Mesajele se șterg la 24h după ultimul mesaj</strong></p>
  {error&&<p className="formerror" role="alert">{error}</p>}
  <div className="conversation-messages" aria-live="polite">{!conversation?.messages.length?<p className="conversation-empty">Începeți firesc — poate chiar cu invitația la o cafea.</p>:conversation.messages.map(message=><div className={`message-row ${message.sender===role?"mine":"theirs"}`} key={message.id}><Image src={avatar(message.sender)} alt="" width={42} height={42} unoptimized/><article><p>{message.text}</p><time>{new Date(message.createdAt).toLocaleTimeString("ro-RO",{hour:"2-digit",minute:"2-digit"})}{message.sender===role&&" ✓✓"}</time></article></div>)}</div>
  {(meeting&&!editMeeting)?<div className="coffee-call"><div className="coffee-call-title"><span><VideoGlyph/></span><div><b>{meeting.status==="propusa"?"Întâlnire video propusă":"O Cafea în Doi"}</b><small>{new Date(meeting.startsAt).toLocaleString("ro-RO",{weekday:"short",hour:"2-digit",minute:"2-digit"})} · aproximativ {meeting.plannedMinutes} min</small></div></div>{meeting.status==="propusa"&&meeting.proposer!==role&&<div className="coffee-actions"><button onClick={()=>request("PATCH",{action:"respond",status:"acceptata"})} disabled={busy}>Acceptă</button><button className="ghost" onClick={()=>setEditMeeting(true)}>Propune altă oră</button></div>}{meeting.status==="propusa"&&meeting.proposer===role&&<p className="coffee-waiting">Așteptăm răspunsul lui {partnerName}.</p>}{meeting.status==="acceptata"&&<button className="coffee-start" onClick={join} disabled={busy}><VideoGlyph/> Începe o Cafea în Doi</button>}<small className="coffee-note">ⓘ Durata este orientativă. Apelul nu se închide automat.</small></div>:<MeetingForm propose={propose} busy={busy} cancel={meeting?()=>setEditMeeting(false):undefined}/>} 
  {conversation?.expiresAt&&<div className="conversation-expiry"><span/><p>◷ Sesiunea expiră peste <strong>{hours}h {minutes}min</strong></p><span/></div>}
  {meeting?.status==="acceptata"&&<button className="conversation-main-call" onClick={join} disabled={busy}><VideoGlyph/> Începe o Cafea în Doi</button>}
  <form className="conversation-compose" onSubmit={send}><button type="button" className="compose-plus" aria-label="Adaugă">+</button><label className="sr-only" htmlFor={`message-${role}`}>Mesaj</label><textarea id={`message-${role}`} value={text} onChange={e=>setText(e.target.value)} maxLength={2000} placeholder="Scrie un mesaj…" required/><button className="compose-send" disabled={busy||!text.trim()} aria-label="Trimite">➤</button></form>
  {call&&<VideoCall call={call} close={()=>setCall(null)}/>} 
 </section>
}

function MeetingForm({propose,busy,cancel}:{propose:(e:FormEvent<HTMLFormElement>)=>Promise<void>;busy:boolean;cancel?:()=>void}){return <form className="coffee-propose" onSubmit={propose}><strong>Propune o întâlnire video</strong><label>Data și ora<input name="startsAt" type="datetime-local" required/></label><label>Durată orientativă<select name="plannedMinutes" defaultValue="30"><option value="15">15 minute</option><option value="30">30 minute</option><option value="60">60 minute</option><option value="90">90 minute</option></select></label><div>{cancel&&<button type="button" className="ghost" onClick={cancel}>Renunță</button>}<button disabled={busy}>Trimite propunerea</button></div><small>Apelul poate continua oricât doriți.</small></form>}
function VideoCall({call,close}:{call:Call;close:()=>void}){const host=useRef<HTMLDivElement>(null);useEffect(()=>{let frame:{init:(o:Record<string,unknown>,e:HTMLElement)=>Promise<void>|void;leaveMeeting?:()=>void}|undefined,cancelled=false;async function start(){if(!window.MeteredFrame)await new Promise<void>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[data-metered="true"]');if(existing){if(window.MeteredFrame)resolve();else existing.addEventListener("load",()=>resolve(),{once:true});return}const script=document.createElement("script");script.src="https://cdn.metered.ca/sdk/frame/1.4.3/sdk-frame.min.js";script.dataset.metered="true";script.onload=()=>resolve();script.onerror=()=>reject(new Error("SDK video indisponibil"));document.head.appendChild(script)});if(cancelled||!host.current||!window.MeteredFrame)return;frame=new window.MeteredFrame();await frame.init({roomURL:call.roomURL,accessToken:call.accessToken,width:"100%",height:"100%",autoJoin:true,joinVideoOn:false,joinAudioOn:false,showInviteBox:false,disableChat:true,disableScreenSharing:true},host.current)}start();return()=>{cancelled=true;frame?.leaveMeeting?.()}},[call]);return <div className="video-overlay" role="dialog" aria-modal="true" aria-label="Cafea în Doi"><div className="video-dialog"><header><div><b>☕ Cafea în Doi</b><small>Apelul nu se închide automat</small></div><button onClick={close} aria-label="Închide apelul">×</button></header><div ref={host} className="video-host"/></div></div>}
function VideoGlyph(){return <span className="video-glyph" aria-hidden="true"><i/></span>}
