"use client";
import {useCallback,useEffect,useState} from "react";
import type {Invitation,InvitationStatus} from "../lib/invitations";
const labels:Record<InvitationStatus,string>={noua:"Nouă",in_conversatie:"În conversație",inchisa:"Închisă"};
function manualWhatsAppLink(invitation:Invitation){
 const phone=invitation.whatsapp.replace(/\D/g,"");
 if(!/^[1-9]\d{7,14}$/.test(phone)||!invitation.slotStart)return null;
 const when=new Intl.DateTimeFormat("ro-RO",{timeZone:"Europe/Bucharest",dateStyle:"full",timeStyle:"short"}).format(new Date(invitation.slotStart));
 const message=`Bună, ${invitation.prenume}! ☕ Îți confirm întâlnirea pentru ${when} (ora României). Abia aștept să bem o cafea în doi! Adrian · cafeaindoi.eu`;
 return `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;
}
export default function InvitationAdmin(){
 const [rows,setRows]=useState<Invitation[]>([]);
 const [loading,setLoading]=useState(true);
 const [busy,setBusy]=useState<string|null>(null);
 const [error,setError]=useState("");
 const [slots,setSlots]=useState<{start:string;label:string}[]>([]);
 useEffect(()=>{fetch("/api/program",{cache:"no-store"}).then(r=>r.json()).then(x=>setSlots(x.slots||[])).catch(()=>{})},[]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/admin/invitatii",{cache:"no-store"});if(!r.ok)throw Error("Invitațiile nu au putut fi încărcate.");const data=await r.json();setRows(data.invitations)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function change(id:string,status:InvitationStatus){setBusy(id);setError("");try{const r=await fetch("/api/admin/invitatii",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})});if(!r.ok)throw Error("Starea nu a putut fi schimbată.");setRows(old=>old.map(x=>x.id===id?{...x,status}:x))}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 async function booking(id:string,bookingStatus:"confirmed"|"declined",slotStart?:string){setBusy(id);setError("");try{const r=await fetch("/api/admin/invitatii",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,bookingStatus,slotStart})});const x=await r.json();if(!r.ok)throw Error(x.error||"Confirmarea nu a reușit.");setRows(old=>old.map(row=>row.id===id?x.invitation:row));if(x.notificationWarning)setError(x.notificationWarning);const slotsResponse=await fetch("/api/program",{cache:"no-store"});if(slotsResponse.ok)setSlots((await slotsResponse.json()).slots)}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 async function resend(id:string){setBusy(id);setError("");try{const r=await fetch("/api/admin/invitatii",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,notify:true})});const x=await r.json();if(!r.ok)throw Error(x.error||"Emailul nu a fost trimis.");setRows(old=>old.map(row=>row.id===id?x.invitation:row))}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 async function remove(id:string){if(!confirm("Ștergi definitiv invitația și eventuala prezentare vizuală din dashboard? Emailul primit se șterge separat."))return;setBusy(id);setError("");try{const r=await fetch("/api/admin/invitatii?id="+encodeURIComponent(id),{method:"DELETE"});if(!r.ok)throw Error("Invitația nu a putut fi ștearsă.");setRows(old=>old.filter(x=>x.id!==id))}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 return <section className="invitation-admin">
  <div className="invitation-admin-head"><div><h2>Invitații primite</h2><p>{rows.length} invitații salvate în dashboard. Invitațiile anterioare rămân în email.</p></div><button type="button" onClick={()=>void load()}>Actualizează</button></div>
  {error&&<p role="alert" className="formerror">{error}</p>}
  {loading?<p>Se încarcă invitațiile…</p>:rows.length===0?<p>Nu există invitații salvate încă.</p>:<div className="invitation-admin-list">{rows.map(row=><article className="invitation-admin-card" key={row.id}>
   {row.photoType?.startsWith("video/")?<video src={`/api/admin/invitatii/${row.id}/photo`} muted playsInline controls preload="metadata" aria-label={`Prezentarea video trimisă de ${row.prenume}`}/>:row.photoType?<img src={`/api/admin/invitatii/${row.id}/photo`} alt={`Selfie trimis de ${row.prenume}`} loading="lazy"/>:<div className="invitation-no-photo" aria-label="Invitație fără prezentare vizuală"><span>☕</span><small>Fără prezentare</small></div>}
   <div><div className="invitation-admin-title"><h3>{row.prenume}, {row.varsta} ani</h3><span>{labels[row.status]}</span></div><p>{row.localitate}, {row.tara} · {new Date(row.createdAt).toLocaleString("ro-RO")}</p><p className="invitation-admin-about">{row.despre}</p>{row.email&&<p>Email: <a href={`mailto:${row.email}`}>{row.email}</a></p>}{row.slotStart&&<div className="booking-admin"><strong>Cafea propusă: {new Intl.DateTimeFormat("ro-RO",{timeZone:"Europe/Bucharest",dateStyle:"full",timeStyle:"short"}).format(new Date(row.slotStart))} (ora României)</strong><p>Stare: {row.bookingStatus==="confirmed"?"Confirmată":row.bookingStatus==="declined"?"Refuzată":"Așteaptă confirmarea"}</p><label>Schimbă ora <select defaultValue="" disabled={busy===row.id} onChange={e=>{if(e.target.value)void booking(row.id,"confirmed",e.target.value)}}><option value="">Alege alt interval…</option>{slots.map(slot=><option value={slot.start} key={slot.start}>{slot.label}</option>)}</select></label><div className="invitation-admin-actions"><button disabled={busy===row.id||row.bookingStatus==="confirmed"} onClick={()=>void booking(row.id,"confirmed")}>Confirmă ora propusă</button><button disabled={busy===row.id||row.bookingStatus==="declined"} onClick={()=>void booking(row.id,"declined")}>Refuză propunerea</button></div><p className="booking-email-status">{row.bookingStatus==="confirmed"?row.confirmationSentAt?"✓ Emailul de confirmare a fost trimis.":row.email?"Emailul de confirmare nu a fost trimis.":"Nu există adresă de email pentru această invitație.":"Confirmarea pe email pleacă după ce accepți ora."}</p>{row.bookingStatus==="confirmed"&&row.email&&<button type="button" disabled={busy===row.id} onClick={()=>void resend(row.id)}>Retrimite emailul</button>}{row.whatsappOptIn&&row.bookingStatus==="confirmed"&&<><p className="booking-email-status">Deschide mesajul pregătit în WhatsApp și apasă Trimite. Site-ul nu trimite automat acest mesaj.</p>{manualWhatsAppLink(row)&&<a className="manual-whatsapp-link" href={manualWhatsAppLink(row)!} target="_blank" rel="noopener noreferrer">Deschide confirmarea în WhatsApp ↗</a>}</>}<small>Dacă alegi altă oră, emailul de confirmare se actualizează. Pentru WhatsApp, deschide din nou mesajul pregătit.</small></div>}<a href={`https://wa.me/${row.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noopener noreferrer">WhatsApp: {row.whatsapp} ↗</a><div className="invitation-admin-actions"><label>Stare <select value={row.status} disabled={busy===row.id} onChange={e=>void change(row.id,e.target.value as InvitationStatus)}>{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="button" disabled={busy===row.id} onClick={()=>void remove(row.id)}>Șterge</button></div></div>
  </article>)}</div>}
 </section>
}
