"use client";
import {useEffect,useState} from "react";
function decodeKey(key:string){const base64=key.replace(/-/g,"+").replace(/_/g,"/"),padded=base64.padEnd(Math.ceil(base64.length/4)*4,"="),raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
export default function PartnerPushSettings(){
 const [config,setConfig]=useState<{configured:boolean;publicKey:string}|null>(null),[enabled,setEnabled]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const response=await fetch("/api/povestea-noastra/push",{cache:"no-store"}),value=await response.json();if(!response.ok)throw Error(value.error);if(!active)return;setConfig(value);if(!("serviceWorker" in navigator))return;const registration=await navigator.serviceWorker.getRegistration(),subscription=await registration?.pushManager.getSubscription();if(!subscription)return;const sync=await fetch("/api/povestea-noastra/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(subscription)});if(!sync.ok)throw Error((await sync.json()).error||"Telefonul nu a putut fi sincronizat.");if(active){setEnabled(true);setMessage("Telefonul tău este sincronizat și poate primi notificări.")}}catch(e){if(active)setMessage(e instanceof Error?e.message:"Notificările nu pot fi încărcate.")}})();return()=>{active=false}},[]);
 async function activate(){setMessage("");try{if(!config?.configured)throw Error("Notificările nu sunt disponibile momentan.");if(!window.isSecureContext)throw Error("Notificările necesită conexiune HTTPS.");if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw Error("Browserul nu acceptă notificări push.");if(Notification.permission==="denied")throw Error("Notificările sunt blocate în Chrome. Deschide Setări site → Notificări → Permite.");const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Permisiunea pentru notificări nu a fost acordată.");const registration=await navigator.serviceWorker.register("/sw.js",{scope:"/",updateViaCache:"none"});await registration.update();const ready=await navigator.serviceWorker.ready;let sub=await ready.pushManager.getSubscription();if(!sub)sub=await ready.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(config.publicKey)});const r=await fetch("/api/povestea-noastra/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sub)});if(!r.ok)throw Error((await r.json()).error||"Activarea a eșuat.");setEnabled(true);setMessage("Notificările sunt active pe acest telefon.")}catch(e){setMessage((e as Error).message)}}
 async function disable(){try{const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(sub){await fetch("/api/povestea-noastra/push",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe()}setEnabled(false);setMessage("Notificările sunt dezactivate pe acest telefon.")}catch(e){setMessage((e as Error).message)}}
 async function test(){try{const r=await fetch("/api/povestea-noastra/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({test:true})}),x=await r.json();if(!r.ok)throw Error(x.error);setMessage(x.sent?"Notificarea de test a fost trimisă.":"Telefonul nu a putut primi testul. Reactivează notificările.")}catch(e){setMessage((e as Error).message)}}
 return <section className="portal-card push-settings"><span className="eyebrow">Notificări</span><h2>Primește noutățile pe telefon</h2><p>Activează notificările pentru mesajele lui Adrian, propunerile de cafea și apelurile video, chiar dacă pagina este închisă.</p><div className="invitation-admin-actions"><button type="button" className="btn" onClick={()=>void activate()} disabled={!config?.configured||enabled}>{enabled?"Active pe acest telefon":"Activează notificările"}</button><button type="button" onClick={()=>void test()} disabled={!enabled}>Trimite un test</button>{enabled&&<button type="button" onClick={()=>void disable()}>Dezactivează</button>}</div>{message&&<p role="status">{message}</p>}</section>
}
