"use client";
import {useEffect,useState} from "react";
function decodeKey(key:string){const raw=atob(key.replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
export default function PushSettings(){
 const [config,setConfig]=useState<{configured:boolean;publicKey:string}|null>(null),[enabled,setEnabled]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/push",{cache:"no-store"}).then(r=>r.json()).then(setConfig).catch(()=>setMessage("Setările push nu pot fi încărcate."));if("serviceWorker" in navigator)navigator.serviceWorker.getRegistration("/").then(r=>r?.pushManager.getSubscription()).then(s=>setEnabled(!!s)).catch(()=>{})},[]);
 async function activate(){setMessage("");try{if(!config?.configured)throw Error("Cheile push trebuie configurate pe server.");if(!("serviceWorker" in navigator)||!("PushManager" in window)||!("Notification" in window))throw Error("Browserul nu acceptă notificări push.");const permission=await Notification.requestPermission();if(permission!=="granted")throw Error("Permisiunea pentru notificări nu a fost acordată.");const registration=await navigator.serviceWorker.register("/sw.js",{scope:"/"});const ready=await navigator.serviceWorker.ready;let sub=await ready.pushManager.getSubscription();if(!sub)sub=await ready.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(config.publicKey)});const r=await fetch("/api/admin/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(sub)});if(!r.ok)throw Error((await r.json()).error||"Abonarea a eșuat.");setEnabled(true);setMessage("Notificările sunt active pe acest telefon.")}catch(e){setMessage((e as Error).message)}}
 async function disable(){try{const reg=await navigator.serviceWorker.ready;const sub=await reg.pushManager.getSubscription();if(sub){await fetch("/api/admin/push",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:sub.endpoint})});await sub.unsubscribe()}setEnabled(false);setMessage("Notificările sunt dezactivate pe acest telefon.")}catch(e){setMessage((e as Error).message)}}
 async function test(){try{const r=await fetch("/api/admin/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({test:true})});const x=await r.json();if(!r.ok)throw Error(x.error);setMessage(x.sent?"Notificarea de test a fost trimisă.":"Nu există încă niciun telefon abonat.")}catch(e){setMessage((e as Error).message)}}
 return <section className="schedule-admin push-settings"><h2>Notificări pe telefon</h2><p>Deschide această pagină din Chrome pe telefon, autentifică-te în admin și apasă „Activează”. Vei primi notificări pentru invitații noi chiar dacă pagina nu este deschisă.</p>{config&&!config.configured?<p role="status">Notificările nu pot fi activate momentan. Verifică stocarea privată.</p>:<div className="invitation-admin-actions"><button type="button" onClick={()=>void activate()} disabled={!config?.configured||enabled}>{enabled?"Active pe acest telefon":"Activează pe acest telefon"}</button><button type="button" onClick={()=>void test()} disabled={!config?.configured||!enabled}>Trimite test</button>{enabled&&<button type="button" onClick={()=>void disable()}>Dezactivează</button>}</div>}{message&&<p role="status">{message}</p>}</section>
}
