"use client";
import {useEffect,useState} from "react";
import type {Schedule} from "../lib/schedule";
const names=["Duminică","Luni","Marți","Miercuri","Joi","Vineri","Sâmbătă"];
export default function ScheduleAdmin(){
 const [value,setValue]=useState<Schedule|null>(null),[blocked,setBlocked]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/admin/program",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error("Programul nu poate fi încărcat.");return r.json()}).then(x=>{setValue(x.schedule);setBlocked(x.schedule.blockedDates.join("\n"))}).catch(e=>setMessage(e.message))},[]);
 async function save(){if(!value)return;setMessage("");try{const r=await fetch("/api/admin/program",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...value,blockedDates:blocked.split(/[\s,]+/).filter(Boolean)})});const x=await r.json();if(!r.ok)throw Error(x.error);setValue(x.schedule);setMessage("Programul a fost salvat.")}catch(e){setMessage((e as Error).message)}}
 return <section className="schedule-admin"><h2>Programul pentru cafea</h2><p>Orele sunt în fusul Germaniei (Europe/Berlin). Sunt afișate intervalele din următoarele 14 zile, cu cel puțin 24 de ore înainte.</p>{!value?<p>{message||"Se încarcă…"}</p>:<><label className="check"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/> Permite rezervări noi</label><fieldset><legend>Zile disponibile</legend>{names.map((name,day)=><label className="check" key={day}><input type="checkbox" checked={value.days.includes(day)} onChange={e=>setValue({...value,days:e.target.checked?[...value.days,day]:value.days.filter(x=>x!==day)})}/>{name}</label>)}</fieldset><div className="schedule-admin-row"><label>De la <input type="time" step="1800" value={value.start} onChange={e=>setValue({...value,start:e.target.value})}/></label><label>Până la <input type="time" step="1800" value={value.end} onChange={e=>setValue({...value,end:e.target.value})}/></label><label>Durata <select value={value.duration} onChange={e=>setValue({...value,duration:Number(e.target.value) as 30|60})}><option value={30}>30 minute</option><option value={60}>60 minute</option></select></label></div><label>Zile blocate (câte o dată YYYY-MM-DD pe rând)<textarea value={blocked} onChange={e=>setBlocked(e.target.value)} placeholder="2026-10-01"/></label><button className="btn" type="button" onClick={()=>void save()}>Salvează programul</button>{message&&<p role="status">{message}</p>}</>}</section>
}
