import {cookies,headers} from "next/headers";
import {NextResponse} from "next/server";
import {PORTAL_COOKIE,verifyPortalSession} from "../../../lib/portal-auth";
import {readInvitation,updateJourney,type Challenge,type PhysicalMeeting,type SharedExperience} from "../../../lib/invitations";
export const runtime="nodejs";
async function current(){return verifyPortalSession((await cookies()).get(PORTAL_COOKIE)?.value)}
function allowedOrigin(origin:string|null){return !origin||origin==="https://www.cafeaindoi.eu"||origin==="https://cafeaindoi.eu"}
export async function GET(){const id=await current();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const invitation=await readInvitation(id);if(!invitation||invitation.portalAccessStatus!=="active")return NextResponse.json({error:"Unauthorized"},{status:401});return NextResponse.json({invitation},{headers:{"Cache-Control":"private, no-store"}})}
export async function PATCH(req:Request){const id=await current();if(!id||!allowedOrigin((await headers()).get("origin")))return NextResponse.json({error:"Unauthorized"},{status:401});const invitation=await readInvitation(id);if(!invitation||invitation.portalAccessStatus!=="active")return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await req.json();if(body.action==="add_challenge"){const title=String(body.title||"").trim().slice(0,120),description=String(body.description||"").trim().slice(0,600);if(!title)return NextResponse.json({error:"Completează provocarea."},{status:400});const challenge:Challenge={id:crypto.randomUUID(),proposer:"ea",title,description:description||undefined,status:"propusa",createdAt:new Date().toISOString()};return NextResponse.json({invitation:await updateJourney(id,{challenges:[...(invitation.challenges||[]),challenge]})})}if(body.action==="challenge_status"){const status=String(body.status) as Challenge["status"];if(!["acceptata","finalizata","refuzata"].includes(status))return NextResponse.json({error:"Stare invalidă."},{status:400});return NextResponse.json({invitation:await updateJourney(id,{challenges:(invitation.challenges||[]).map(x=>x.id===body.challengeId?{...x,status}:x)})})}if(body.action==="meeting_response"&&invitation.physicalMeeting){const status=body.accept===true?"confirmata":"anulata";const meeting:PhysicalMeeting={...invitation.physicalMeeting,status};return NextResponse.json({invitation:await updateJourney(id,{physicalMeeting:meeting})})}if(body.action==="experience_response"&&invitation.sharedExperience){const status=body.accept===true?"acceptata":"anulata";const experience:SharedExperience={...invitation.sharedExperience,status};return NextResponse.json({invitation:await updateJourney(id,{sharedExperience:experience})})}return NextResponse.json({error:"Acțiune invalidă."},{status:400})}catch{return NextResponse.json({error:"Actualizarea nu a reușit."},{status:400})}}
