import {createHash,randomBytes,timingSafeEqual} from "crypto";
import {createSupabaseAdmin} from "./supabase";
import {hashAdminPassword,verifyAdminPassword} from "./admin-password";
export {hashAdminPassword,verifyAdminPassword} from "./admin-password";

const PASSWORD_KEY="admin_password_hash",RESET_KEY="admin_password_reset";
const equal=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
export const adminEmail=()=>String(process.env.ADMIN_EMAIL||process.env.INVITATION_TO_EMAIL||"").trim().toLowerCase();

export async function authenticateAdmin(email:string,password:string){if(!adminEmail()||!equal(email.trim().toLowerCase(),adminEmail()))return false;const db=createSupabaseAdmin(),{data,error}=await db.from("app_settings").select("value").eq("key",PASSWORD_KEY).maybeSingle();if(error)throw error;const stored=typeof data?.value?.hash==="string"?data.value.hash:"";if(stored)return verifyAdminPassword(password,stored);const legacy=process.env.ADMIN_PASSWORD||"";if(!legacy||!equal(password,legacy))return false;const hash=await hashAdminPassword(password),{error:saveError}=await db.from("app_settings").upsert({key:PASSWORD_KEY,value:{hash},updated_at:new Date().toISOString()});if(saveError)throw saveError;return true}

export async function createAdminReset(){const token=randomBytes(32).toString("base64url"),tokenHash=createHash("sha256").update(token).digest("hex"),expiresAt=new Date(Date.now()+30*60_000).toISOString(),{error}=await createSupabaseAdmin().from("app_settings").upsert({key:RESET_KEY,value:{tokenHash,expiresAt},updated_at:new Date().toISOString()});if(error)throw error;return {token,expiresAt}}

export async function resetAdminPassword(token:string,password:string){if(!/^[A-Za-z0-9_-]{40,60}$/.test(token))return false;const db=createSupabaseAdmin(),{data,error}=await db.from("app_settings").select("value").eq("key",RESET_KEY).maybeSingle();if(error)throw error;const tokenHash=createHash("sha256").update(token).digest("hex"),stored=data?.value as {tokenHash?:string;expiresAt?:string}|undefined;if(!stored?.tokenHash||!stored.expiresAt||Date.parse(stored.expiresAt)<Date.now()||!equal(tokenHash,stored.tokenHash))return false;const {data:deleted,error:deleteError}=await db.from("app_settings").delete().eq("key",RESET_KEY).contains("value",{tokenHash}).select("key");if(deleteError)throw deleteError;if(!deleted?.length)return false;const hash=await hashAdminPassword(password),{error:saveError}=await db.from("app_settings").upsert({key:PASSWORD_KEY,value:{hash},updated_at:new Date().toISOString()});if(saveError)throw saveError;return true}

export async function sendAdminResetEmail(token:string){const key=process.env.RESEND_API_KEY_V2||process.env.RESEND_API_KEY,from=process.env.INVITATION_FROM_EMAIL||"Cafea în Doi <onboarding@resend.dev>",to=adminEmail();if(!key||!to)throw new Error("Emailul de recuperare nu este configurat.");const url=`https://www.cafeaindoi.eu/admin/resetare?token=${encodeURIComponent(token)}`,r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json","Idempotency-Key":`admin-reset-${createHash("sha256").update(token).digest("hex").slice(0,32)}`},body:JSON.stringify({from,to:[to],subject:"Schimbă parola de administrator · Cafea în Doi",text:`Ai solicitat schimbarea parolei de administrator. Linkul este valabil 30 de minute:\n\n${url}\n\nDacă nu ai solicitat schimbarea, ignoră acest mesaj.`,html:`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto;color:#33241f"><h2>Cafea în Doi</h2><p>Ai solicitat schimbarea parolei de administrator.</p><p><a style="display:inline-block;padding:12px 18px;border-radius:10px;background:#4b2d1f;color:#fff;text-decoration:none;font-weight:bold" href="${url}">Alege o parolă nouă</a></p><p>Linkul este valabil 30 de minute și poate fi folosit o singură dată.</p><p>Dacă nu ai solicitat schimbarea, ignoră acest mesaj.</p></div>`})});if(!r.ok)throw new Error("Emailul de recuperare nu a putut fi trimis.")}
