import {createSupabaseAdmin} from "./supabase";

export type AudioCallSignal={id:string;state:"ringing"|"connected"|"ended";caller:"adrian"|"ea";offer?:RTCSessionDescriptionInit;answer?:RTCSessionDescriptionInit;createdAt:string;updatedAt:string};
const validId=(id:string)=>/^[0-9a-f-]{36}$/i.test(id);
const validDescription=(value:unknown,type:"offer"|"answer"):value is RTCSessionDescriptionInit=>{if(!value||typeof value!=="object")return false;const item=value as Record<string,unknown>;return item.type===type&&typeof item.sdp==="string"&&item.sdp.length>20&&item.sdp.length<100_000};
const map=(row:any):AudioCallSignal=>({id:row.record.callId,state:row.status,caller:row.record.caller,offer:row.record.offer,answer:row.record.answer,createdAt:row.created_at,updatedAt:row.updated_at});
async function notifyConversation(id:string){await createSupabaseAdmin().from("conversations").update({updated_at:new Date().toISOString()}).eq("id",id)}
export async function readAudioCall(id:string){if(!validId(id))return null;const {data,error}=await createSupabaseAdmin().from("content_records").select("*").eq("kind","audio_call").eq("id",id).maybeSingle();if(error)throw error;if(!data||Date.now()-Date.parse(data.updated_at)>2*60*60_000)return null;return map(data)}
export async function startAudioCall(id:string,caller:"adrian"|"ea",offer:unknown){if(!validId(id)||!validDescription(offer,"offer"))throw new Error("Oferta apelului nu este validă.");const now=new Date().toISOString(),record={callId:crypto.randomUUID(),caller,offer},{data,error}=await createSupabaseAdmin().from("content_records").upsert({kind:"audio_call",id,status:"ringing",record,created_at:now,updated_at:now},{onConflict:"kind,id"}).select("*").single();if(error)throw error;await notifyConversation(id);return map(data)}
export async function answerAudioCall(id:string,role:"adrian"|"ea",callId:string,answer:unknown){if(!validId(id)||!validId(callId)||!validDescription(answer,"answer"))throw new Error("Răspunsul apelului nu este valid.");const db=createSupabaseAdmin(),{data:current,error:readError}=await db.from("content_records").select("*").eq("kind","audio_call").eq("id",id).single();if(readError||current.record.callId!==callId||current.record.caller===role||current.status!=="ringing")throw new Error("Apelul nu mai este disponibil.");const {data,error}=await db.from("content_records").update({status:"connected",record:{...current.record,answer},updated_at:new Date().toISOString()}).eq("kind","audio_call").eq("id",id).select("*").single();if(error)throw error;await notifyConversation(id);return map(data)}
export async function endAudioCall(id:string,callId:string){if(!validId(id)||!validId(callId))throw new Error("Apel invalid.");const db=createSupabaseAdmin(),{data:current}=await db.from("content_records").select("record").eq("kind","audio_call").eq("id",id).maybeSingle();if(!current||current.record.callId!==callId)return null;const {data,error}=await db.from("content_records").update({status:"ended",updated_at:new Date().toISOString()}).eq("kind","audio_call").eq("id",id).select("*").single();if(error)throw error;await notifyConversation(id);return map(data)}
