import {createSupabaseAdmin} from "./supabase";

export type OpinionStatus="pending"|"approved";
export type OpinionRecord={id:string;article:string;articleTitle:string;prenume:string;opinia:string;createdAt:string;status:OpinionStatus;approvedAt?:string};
const KIND="opinion";
export async function savePendingOpinion(input:Omit<OpinionRecord,"id"|"createdAt"|"status">){const record:OpinionRecord={...input,id:crypto.randomUUID(),createdAt:new Date().toISOString(),status:"pending"};const {error}=await createSupabaseAdmin().from("content_records").insert({kind:KIND,id:record.id,status:record.status,slug:record.article,record,created_at:record.createdAt,updated_at:record.createdAt});if(error)throw error;return record}
export async function listOpinions(status:OpinionStatus){const {data,error}=await createSupabaseAdmin().from("content_records").select("record").eq("kind",KIND).eq("status",status).order("updated_at",{ascending:false}).limit(1000);if(error)throw error;const rows=(data||[]).map(x=>x.record as OpinionRecord);return rows.sort((a,b)=>new Date(b.approvedAt||b.createdAt).getTime()-new Date(a.approvedAt||a.createdAt).getTime())}
export async function listApprovedForArticle(article:string){return (await listOpinions("approved")).filter(x=>x.article===article)}
export async function approveOpinion(id:string){const db=createSupabaseAdmin(),{data,error}=await db.from("content_records").select("record").eq("kind",KIND).eq("id",id).eq("status","pending").maybeSingle();if(error)throw error;const record=data?.record as OpinionRecord|undefined;if(!record)throw new Error("Opinia nu a fost găsită.");const approved:OpinionRecord={...record,status:"approved",approvedAt:new Date().toISOString()};const {error:updateError}=await db.from("content_records").update({status:"approved",record:approved,updated_at:approved.approvedAt}).eq("kind",KIND).eq("id",id);if(updateError)throw updateError;return approved}
export async function rejectOpinion(id:string){const {error}=await createSupabaseAdmin().from("content_records").delete().eq("kind",KIND).eq("id",id).eq("status","pending");if(error)throw error}
export async function deleteApprovedOpinion(id:string){const {error}=await createSupabaseAdmin().from("content_records").delete().eq("kind",KIND).eq("id",id).eq("status","approved");if(error)throw error}
export async function unpublishOpinion(id:string){const db=createSupabaseAdmin(),{data,error}=await db.from("content_records").select("record").eq("kind",KIND).eq("id",id).eq("status","approved").maybeSingle();if(error)throw error;const record=data?.record as OpinionRecord|undefined;if(!record)throw new Error("Opinia nu a fost găsită.");const pending:OpinionRecord={...record,status:"pending"};delete pending.approvedAt;const {error:updateError}=await db.from("content_records").update({status:"pending",record:pending,updated_at:new Date().toISOString()}).eq("kind",KIND).eq("id",id);if(updateError)throw updateError;return pending}
