import {createHash} from "crypto";
import webpush from "web-push";
import {createSupabaseAdmin} from "./supabase";
export type PushRecipient="admin"|"partner";
export type StoredSubscription={endpoint:string;keys:{p256dh:string;auth:string};createdAt:string;recipient?:PushRecipient;invitationId?:string};
type Keys={publicKey:string;privateKey:string};
export async function getPushKeys():Promise<Keys>{const db=createSupabaseAdmin(),{data}=await db.from("app_settings").select("value").eq("key","admin_push_vapid").maybeSingle();if(data?.value)return data.value as Keys;const keys=webpush.generateVAPIDKeys();const {error}=await db.from("app_settings").insert({key:"admin_push_vapid",value:keys});if(!error)return keys;const concurrent=await db.from("app_settings").select("value").eq("key","admin_push_vapid").single();if(concurrent.error)throw concurrent.error;return concurrent.data.value as Keys}
const endpointHash=(endpoint:string)=>createHash("sha256").update(endpoint).digest("hex");
const allowedHost=(host:string)=>host==="fcm.googleapis.com"||host==="updates.push.services.mozilla.com"||host==="web.push.apple.com"||host.endsWith(".push.apple.com")||host.endsWith(".push.services.mozilla.com")||host.endsWith(".googleapis.com");
export function validateSubscription(value:any):value is StoredSubscription{try{const url=new URL(value?.endpoint);return url.protocol==="https:"&&allowedHost(url.hostname)&&url.username===""&&url.password===""&&url.port===""&&typeof value?.keys?.p256dh==="string"&&/^[A-Za-z0-9_-]{60,150}$/.test(value.keys.p256dh)&&typeof value?.keys?.auth==="string"&&/^[A-Za-z0-9_-]{12,50}$/.test(value.keys.auth)}catch{return false}}
export async function saveSubscription(value:StoredSubscription){const {error}=await createSupabaseAdmin().from("push_subscriptions").upsert({endpoint_hash:endpointHash(value.endpoint),subscription:value,created_at:value.createdAt});if(error)throw error}
export async function deleteSubscription(endpoint:string,owner?:{recipient:PushRecipient;invitationId?:string}){let query=createSupabaseAdmin().from("push_subscriptions").delete().eq("endpoint_hash",endpointHash(endpoint));if(owner)query=query.contains("subscription",owner);const {error}=await query;if(error)throw error}
export async function listSubscriptions(target:{recipient?:PushRecipient;invitationId?:string}={}){const {data,error}=await createSupabaseAdmin().from("push_subscriptions").select("subscription").limit(1000);if(error)throw error;return (data||[]).map(x=>x.subscription as StoredSubscription).filter(sub=>{const recipient=sub.recipient||"admin";return (!target.recipient||recipient===target.recipient)&&(!target.invitationId||sub.invitationId===target.invitationId)})}
export async function sendPush(title:string,body:string,options:{url?:string;tag?:string;recipient?:PushRecipient;invitationId?:string}={}){const keys=await getPushKeys();webpush.setVapidDetails("mailto:contact@cafeaindoi.eu",keys.publicKey,keys.privateKey);const subscriptions=await listSubscriptions({recipient:options.recipient||"admin",invitationId:options.invitationId});let sent=0,failed=0;await Promise.all(subscriptions.map(async sub=>{try{await webpush.sendNotification({endpoint:sub.endpoint,keys:sub.keys},JSON.stringify({title,body,url:options.url||"/admin/invitatii",tag:options.tag||"cafeaindoi"}),{TTL:86400,urgency:"high"});sent++}catch(error){failed++;const status=(error as {statusCode?:number}).statusCode;if(status===404||status===410)await deleteSubscription(sub.endpoint);else console.error("[push] SEND_ERROR",status||error)}}));return {sent,failed,total:subscriptions.length}}
