import {NextResponse} from "next/server";
export const runtime="nodejs";
const WINDOW=60_000,MAX=5,MAX_PHOTO=5*1024*1024,PHOTO_TYPES=new Set(["image/jpeg","image/png","image/webp"]);const hits=new Map<string,{n:number,t:number}>();
const safe=(s:string)=>s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]||c));
export async function POST(req:Request){try{
 const ip=req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||"unknown",now=Date.now(),h=hits.get(ip);if(h&&now-h.t<WINDOW&&h.n>=MAX)return NextResponse.json({ok:false,error:"Prea multe încercări. Încearcă din nou peste un minut."},{status:429});hits.set(ip,!h||now-h.t>=WINDOW?{n:1,t:now}:{n:h.n+1,t:h.t});
 const origin=req.headers.get("origin"),allowed=new Set(["https://www.cafeaindoi.eu","https://cafeaindoi.eu"]);if(origin&&!allowed.has(origin))return NextResponse.json({ok:false,error:"Cerere nepermisă."},{status:403});
 const d=await req.formData();if(String(d.get("website")||"").trim())return NextResponse.json({ok:true});
 const prenume=String(d.get("prenume")||"").trim().slice(0,80),localitate=String(d.get("localitate")||"").trim().slice(0,120),tara=String(d.get("tara")||"").trim().slice(0,80),despre=String(d.get("despre")||"").trim().slice(0,3000),whatsapp=String(d.get("whatsapp")||"").trim().slice(0,25),varsta=Number(d.get("varsta")),ageOk=d.get("ageOk")==="on",privacyOk=d.get("privacyOk")==="on",photo=d.get("photo");
 const whatsappOk=/^\+?[0-9][0-9 ()-]{6,24}$/.test(whatsapp)&&whatsapp.replace(/\D/g,"").length>=7&&whatsapp.replace(/\D/g,"").length<=15;
 if(!prenume||!localitate||!tara||!despre||!whatsapp||!Number.isInteger(varsta)||varsta<18||varsta>99||!whatsappOk||!ageOk||!privacyOk)return NextResponse.json({ok:false,error:"Verifică toate câmpurile obligatorii."},{status:400});
 if(!(photo instanceof File)||photo.size===0)return NextResponse.json({ok:false,error:"Fotografia este obligatorie."},{status:400});
 if(!PHOTO_TYPES.has(photo.type))return NextResponse.json({ok:false,error:"Fotografia trebuie să fie JPG, PNG sau WebP."},{status:400});
 if(photo.size>MAX_PHOTO)return NextResponse.json({ok:false,error:"Fotografia poate avea maximum 5 MB."},{status:413});
 const key=process.env.RESEND_API_KEY_V2,to=process.env.INVITATION_TO_EMAIL,from=process.env.INVITATION_FROM_EMAIL||"Cafea în Doi <onboarding@resend.dev>";if(!key||!to)return NextResponse.json({ok:false,error:"Configurația de email este incompletă."},{status:503});
 const ext=photo.type==="image/png"?"png":photo.type==="image/webp"?"webp":"jpg",filename=`fotografie-${prenume.replace(/[^a-zA-Z0-9_-]/g,"-")||"invitatie"}.${ext}`,content=Buffer.from(await photo.arrayBuffer()).toString("base64");
 const subject="Cafea în Doi — invitație nouă";const text=["Invitație nouă Cafea în Doi","",`Prenume: ${prenume}`,`Vârstă: ${varsta}`,`Localitate: ${localitate}`,`Țară: ${tara}`,`WhatsApp: ${whatsapp}`,"","Despre ea:",despre,"","Fotografia este atașată acestui email."].join("\n");const waDigits=whatsapp.replace(/[^0-9]/g,"");
 const html=`<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;color:#33241f"><h2>☕ Cafea în Doi</h2><p>Ai primit o invitație nouă.</p><div style="border:1px solid #eaded8;border-radius:14px;padding:20px;background:#fffaf7"><p><strong>Prenume:</strong> ${safe(prenume)}</p><p><strong>Vârstă:</strong> ${varsta}</p><p><strong>Localitate:</strong> ${safe(localitate)}</p><p><strong>Țară:</strong> ${safe(tara)}</p><p><strong>WhatsApp:</strong> ${safe(whatsapp)}</p><p><strong>Despre ea:</strong><br>${safe(despre).replace(/\n/g,"<br>")}</p><p><strong>Fotografie:</strong> atașată emailului.</p>${waDigits?`<p><a href="https://wa.me/${waDigits}">Deschide WhatsApp</a></p>`:""}</div></div>`;
 const r=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,text,html,attachments:[{filename,content,content_type:photo.type}]})});if(!r.ok){console.error("[invitatie] RESEND_ERROR",await r.text());return NextResponse.json({ok:false,error:"Mesajul nu a putut fi trimis."},{status:502})}return NextResponse.json({ok:true});
 }catch(e){console.error("[invitatie] INVALID_REQUEST",e);return NextResponse.json({ok:false,error:"Cerere invalidă."},{status:400})}}
