import {NextRequest,NextResponse} from "next/server";
import {authorized} from "../../../../lib/admin-auth";
import {ContactStatus,getContactSettings,listContactMessages,saveContactSettings,updateContactMessage,validateContactSettings} from "../../../../lib/contact";

export const runtime="nodejs";export const dynamic="force-dynamic";
const statuses=new Set<ContactStatus>(["new","in_progress","resolved","archived"]);
const csv=(value:string)=>`"${value.replace(/"/g,'""')}"`;
export async function GET(req:NextRequest){if(!authorized(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{const [messages,settings]=await Promise.all([listContactMessages(),getContactSettings()]);if(req.nextUrl.searchParams.get("format")==="csv"){const lines=[["Data","Nume","Email","Subiect","Mesaj","Stare","Notiță internă"].map(csv).join(","),...messages.map(item=>[item.createdAt,item.name,item.email,item.subject,item.message,item.status,item.internalNote].map(csv).join(","))];return new Response("\ufeff"+lines.join("\n"),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="mesaje-contact-${new Date().toISOString().slice(0,10)}.csv"`}})}return NextResponse.json({messages,settings},{headers:{"Cache-Control":"private, no-store"}})}catch(error){console.error("[admin/contact] GET_ERROR",error);return NextResponse.json({error:"Mesajele nu pot fi încărcate."},{status:503})}}
export async function PATCH(req:NextRequest){if(!authorized(req))return NextResponse.json({error:"Unauthorized"},{status:401});try{const body=await req.json();if(body.type==="settings"){const settings=validateContactSettings(body.settings);if(!settings)return NextResponse.json({error:"Verifică setările introduse."},{status:400});return NextResponse.json({settings:await saveContactSettings(settings)})}const id=String(body.id||""),status=String(body.status||"") as ContactStatus,internalNote=String(body.internalNote||"").trim().slice(0,3000);if(!/^[0-9a-f-]{36}$/i.test(id)||!statuses.has(status))return NextResponse.json({error:"Date invalide."},{status:400});return NextResponse.json({message:await updateContactMessage(id,{status,internalNote})})}catch(error){console.error("[admin/contact] PATCH_ERROR",error);return NextResponse.json({error:"Modificarea nu a putut fi salvată."},{status:503})}}
